spring:
  application:
    name: bank-authentication-service

  datasource:
    url: jdbc:mysql://localhost:3306/bank_data
    username: prithwi
    password: capgemini
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8085